### ISSUE TITLE
Geometry instantiated by a curve does not respect asset transform.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#61] opened 2016-04-13 14:57 UTC
Geometry instantiated by a curve does not respect asset transform. This manifests in generated static mesh components having invalid transform and not be "attached" to the generator asset.
# 

Filed as BUG: #74901 - Geometry instantiated by a curve does not respect asset transform.

**Comment by Yelmond** [comment] 2016-06-24 18:54
This is not quite fixed but there is a workaround.

The issue is that curve inputs are created in world space in Houdini but they are tied to the asset in UE4. This presents a mismatch of how geometry inputs to a SOP asset work. It's a bit of a workflow issue, for sure, that should be fixed at some point. Unfortunately, that's not trivial to do at this point.

There is a relatively simple workaround that should fix this issue. You have to change your asset to be an OBJ asset.

You can do this by marking your instantiated SOP asset as editable and then creating a new asset out of the OBJ that contains your SOP. For each of your SOP inputs, you have to create an **Object Merge SOP** for which you expose the **Object 1** parameter to the top level of your new asset. For curve inputs, you have to make sure the **Transform** parameter on the **Object Merge SOP** is set to **None**.

**Comment by cgrebeld** [comment] 2016-09-27 17:41
Fixed.

**Closed as completed by cgrebeld** 2016-09-27 17:41 UTC
Labels: enhancement, curves, geometry
